### ISSUE TITLE
Can't rename db instance

### ISSUE THREAD

**Issue by Spy-Shifty** [GeoNode/geonode-docker#15] opened 2019-03-22 10:29 UTC
When using docker-compose the database instance has to be "db" because of:
```
def _update_db_connstring():
    user = os.getenv('GEONODE_DATABASE', 'geonode')
    pwd = os.getenv('GEONODE_DATABASE_PASSWORD', 'geonode')
    dbname = os.getenv('GEONODE_DATABASE', 'geonode')
    connstr = 'postgres://{0}:{1}@db:5432/{2}'.format(
        user,
        pwd,
        dbname
    )
    return connstr


def _update_geodb_connstring():
    geouser = os.getenv('GEONODE_GEODATABASE', 'geonode_data')
    geopwd = os.getenv('GEONODE_GEODATABASE_PASSWORD', 'geonode_data')
    geodbname = os.getenv('GEONODE_GEODATABASE', 'geonode_data')
    geoconnstr = 'postgis://{0}:{1}@db:5432/{2}'.format(
        geouser,
        geopwd,
        geodbname
    )
    return geoconnstr
```

Please change the code to some thing like this:

```
def _update_db_connstring():
    geoconnstr = os.getenv('GEONODE_DATABASE_URL', '')
    return geoconnstr


def _update_geodb_connstring():
    geoconnstr = os.getenv('GEONODE_GEODATABASE_URL', '')
    return geoconnstr

```
Where the environment variables are like:
```
GEONODE_DATABASE_URL=postgres://geonode:geonode@geoserver-db:5432/geonode
GEONODE_GEODATABASE_URL=postgres://geonode_data:geonode_data@geoserver-db:5432/geonode_data
```

**Comment by francbartoli** [comment] 2019-07-10 14:31
@Spy-Shifty the database instance is taking the hostname from the service name declared in the docker-compose file. This is by design for docker-compose networking. We actually don't need to have it dynamically defined because it is used only for internal communication among containers. I'm going to close this.

**Closed by francbartoli** 2019-07-10 14:31 UTC

**Comment by ingenieroariel** [comment] 2019-07-10 14:42
Francesco, the snippet of code he linked to has "db" hardcoded. Are you
sure there is a parameter to change it?

**Comment by francbartoli** [comment] 2019-07-10 15:39
Hi @ingenieroariel no there isn’t but that change doesn’t make sense to me. Why should we make it a variable? What’s the benefit?

**Comment by ingenieroariel** [comment] 2019-07-10 16:01
I just checked the actual code, since it is all in tasks.py and that is
tied to the current docker implementation I guess it is okay and end users
can just override it if they need to.

My main gripe was if it was harcoded in GeoNode itself (the django project).
-a
